name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Hello
        run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
  
