name: Label PR as Bug on /bug Comment

on:
  issue_comment:
    types: [created]

jobs:
  label-bug:
    if: github.event.issue.pull_request
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Label PR
        run: python addbugLabel.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_ISSUE_NUMBER: ${{ github.event.issue.number }}
          INPUT_COMMAND: ${{ github.event.comment.body }}
