name: Run Model Report

on:
  issue_comment:
    types: [created]

jobs:
  run-report:
    name: Run model report
    runs-on: ubuntu-latest
    if: (github.event.issue.pull_request != null) && contains(github.event.comment.body, '/wandb')

    steps:
      - name: Get repo contents
        uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install ghapi "wandb[workspaces]"

      - name: Parse value from the command
        id: get-runid-value
        shell: python
        run: |
          import re, os
          comment = os.getenv('PR_COMMENT', '')
          match = re.search(r'/wandb\s+(\S+)', comment)

          with open(os.environ['GITHUB_OUTPUT'], 'a') as f:
              if match:
                  print('VAL_FOUND=true', file=f)
                  print(f'RUN_ID={match.group(1)}', file=f)
              else:
                  print('VAL_FOUND=false', file=f)
        env:
          PR_COMMENT: ${{ github.event.comment.body }}

      - name: Generate the comparison report
        if: steps.get-runid-value.outputs.VAL_FOUND == 'true'
        id: wandb-report
        run: python ./compare_runs.py
        env:
          WANDB_ENTITY: dvir-hayat-kla
          WANDB_PROJECT: cicd-quickstart
          BASELINE_TAG: baseline
          RUN_ID: "${{ steps.get-runid-value.outputs.RUN_ID }}"
          WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}

      - name: Make a comment with the GitHub API
        uses: actions/github-script@v6
        if: steps.wandb-report.outcome == 'success'
        with:
          script: |
            var msg = `A comparison between the linked run and baseline is available [in this report](${process.env.REPORT_URL})`
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: msg
            })
        env:
          REPORT_URL: "${{ steps.wandb-report.outputs.REPORT_URL }}"
